apiVersion: v1
kind: ConfigMap
metadata:
  name: jerney-backend-config
  namespace: jerney
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  PORT: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerney-backend
  namespace: jerney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jerney-backend
  template:
    metadata:
      labels:
        app: jerney-backend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: backend
        image: sumitjeswani/jerney-backend:v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: jerney-backend-config
        - secretRef:
            name: jerney-db-secret
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jerney-backend-svc
  namespace: jerney
spec:
  selector:
    app: jerney-backend
  ports:
  - port: 5000
    targetPort: 5000
